### ISSUE TITLE
My courses search/sort functionality

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#267]
# Overview

The student view of “my courses” does not have a search or sort functionality implemented yet. Below is a view of what the UI should look like.
<img width="1471" alt="my courses search:sort" src="https://github.com/UnlockedLabs/UnlockEdv2/assets/89868388/256fbf69-3e31-4a55-8fb9-35f5836cbeab">

# Relevant files

These should live in the `MyCourses.tsx` file. The handler is in `/backend/src/handlers/dashboard.go` and the call to the database is in `/backend/src/database/user_catalogue.go` . 

# Sorting

Filtering should already partially be available through the different tabs. This needs to be updated to include a few more filters. Users should additionally be able to sort by:

- alphabetically
- progress

# Tasks to complete ticket

- [ ] Update backend api call and table join to query for filtering of courses
- [ ] Update frontend to include search and filter dropdown
- [ ] Connect frontend to backend for search and filter
