### ISSUE TITLE
My progress search/sort functionality

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#268]
# Overview

The student view of “my progress” does not have a sort functionality implemented yet. Below is a view of what the UI should look like. The two sorts that must be added are for courses and for certifications.
<img width="1512" alt="my progress search sort" src="https://github.com/UnlockedLabs/UnlockEdv2/assets/89868388/658fb783-d7b9-487f-8202-88f9b11bf100">

# Relevant files

These should live in the `MyCourses.tsx` file. The handler is in `/backend/src/handlers/dashboard.go` and the call to the database is in `/backend/src/database/dashboard.go` for “all courses” table. The handler for “certificates” is in `/backend/src/handlers/outcomes_handler.go` and call to the database is in `/backend/src/database/outcomes.go`. 

# Sorting

Users should be able to sort/filter by the following in courses:

- alphabetically
- status (completed or in progress)
- grade
- hours spent
- any other you see relevant

Users should be able so sort by the following in certificates:

- date
- alphabetically
- any other you see relevant

# Tasks to complete ticket

- [ ] Update backend api call and table join to query for filtering of courses and certificates
- [ ] Update frontend to include filter dropdown for courses and certificates
- [ ] Connect frontend to backend for filter

**Comment by jtucholski** [comment]
Closed as this was fixed in in PR #348
