### ISSUE TITLE
Revise Resource Management Page to Updated Design

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#363]
# Overview
The resource management page, accessible in the admin portal, needs to be revised to make the page more intuitive to use. The new design reformats the page to include a Preview section to display how the resources would look in the student portal, along with a section on the right hand side which allows the admin to edit resources that currently exist. Below is a short video to demonstrate some of the new features that should be included in this revision. **Please note that this video does not include all features. All features required to complete this ticket will be listed below.**

https://github.com/user-attachments/assets/fba0027d-d763-4599-b763-b312c277c1b0

# Requirements
The updated resource management page should be able to do the following:
### Adding a Category
- You can add a new resource using the plus icon in the top right corner of the "Resources Preview" container. This will open a modal that [looks like this](https://www.figma.com/design/a7VMBAXF2s385ogih8zjzl/Harvard-Mockups-Dark-Mode?node-id=4001-2055&t=K7TLffVrli1elZlM-0) with empty text inputs using the form inputs in `/Components/inputs`

### Modifying a Category
- When a card is selected, a yellow border should be applied to the outside of the card and the resource should appear in the right hand container in "edit mode", aka with all the links as inputs that are directly modifiable. An example of this can be seen [here](https://www.figma.com/design/a7VMBAXF2s385ogih8zjzl/Harvard-Mockups-Dark-Mode?node-id=3997-6876&t=K7TLffVrli1elZlM-0)). 
- There are 4 relevant icons while in edit mode of a specific research. **All icons that do not have words accompanying their function should have a tooltip that explains what they do.** For example, the trash icon should have a tooltip that says "Delete Resource".
    1. Trash icon to delete resource- this is used to delete the selected resource. A confirm delete resource modal should appear before deleting.
    2. Pencil square icon (edit) - this is used to edit the _title of the resource_. The modal should only contain 1 input field. An example can be seen [here](https://www.figma.com/design/a7VMBAXF2s385ogih8zjzl/Harvard-Mockups-Dark-Mode?node-id=4062-6455&t=K7TLffVrli1elZlM-0).
    3. Add link icon - 
    4. Trash icon to delete link (on the right hand side)- deletes that specific link. A confirm delete link modal should appear before deleting.

- When you modify a card, the modification should immediately appear in the right hand side, but remember _these changes are only stored locally for now._ The changes are only published to the backend when the user clicks "Publish Changes".
- Drag and drop the left hand resource cards to change the order of the cards. This would highlight **all the cards impacted by the order change**. For example, if there are 4 resources listed on the left hand side and the admin user moved the 2nd card to the 4th position, cards 2-4 would all be highlighted in yellow.

**Comment by jtucholski** [comment]
**Task List**

- [ ] Refactor `ResourceCard`, `WikipediaCard`, and `KolibriCard` from  `ResourcesSideBar` into individual components.
- [ ] Use the new `ResourceCard` in the `ResourcesManagement` screen to provide a Resources Preview for Administrators.
- [ ] Implement drag-and-drop functionality to rearrange resources in the Preview.
- [ ] Highlight resources that have been reordered with a yellow background.
- [ ] Change the Save button to a "Publish Changes" button with a cloud icon. Clicking this will save changes and reset the highlighted state of the resources in the preview.
- [ ] In the "Add Resource" modal, require the user to input a new resource title, a single link name, and a link URL. Upon submission, the resource appears in the Resources Preview and is highlighted yellow.
- [ ] Implement a new UI with two panes:
  - [ ] The left pane is the Resources Preview component
  - [ ] The right pane is the Modify Resource component
    - [ ] Update the icons to match those provided by the design. Any icons without text should have tooltips (e.g., Trash icon should read "Delete Resource")

**Comment by jtucholski** [comment]
The PR for this has been opened against @PThorpe92's `main` branch.

**Comment by jtucholski** [comment]
Closed as it has been merged into `main`.
