### ISSUE TITLE
Split User Management into Students-only and Admins-only Views

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#382]
We want to be able to manage admins and students separately. To that end, we should split User Management page into Admin Management and Student Management screens. We can obviously remove the 'role' column, so think about what column makes send to replace it with for each of the new screens.

## Subtasks

- [ ] Create a new component for the tab view on My Courses. Use that component within `MyCourses.tsx`.
- [ ] Create separate pages for students and admin management. The new updated figma for this can be found [here](https://www.figma.com/design/a7VMBAXF2s385ogih8zjzl/Harvard-Mockups-Dark-Mode?node-id=4209-5837&node-type=frame&t=WnH7HfVWKEUs9K04-0). Remove the "Role" column in the table, but no other changes need to be made to the table yet. This will be done in a different ticket to update the UI of the page in general.

Separate ticket:

As an Admin, I'd like to be able to click on a student's name in the new Student Management screen and see a dashboard with information about the student. At the very least, we can show some basic information about the student. @nokierae and @chrissantillan are available to discuss what else we'd like to see on that dashboard.

**Comment by corypride** [comment]
@calisio @chrissantillan 
* Which of the tabs "Admin" or "Student" is the default tab?

**Comment by calisio** [comment]
The roles should be displayed as tabs, similar to what it looks like in the My Courses page on the student view (screenshot attached below. Make sure to add in the "Users" title to the top of the page (doesn't exist now). The tabs are not currently a component.

## Subtasks

- [ ] Create a new component for the tab view on My Courses. Use that component within `MyCourses.tsx` and then later in `Users.tsx`
- [ ] Use the tab view within `Users.tsx` to create a similar tabular view as is seen in the My Courses, but with "Admin" and "Student" as the two tabs for now. Remove the "Role" column in the table.

**Comment by calisio** [comment]
To answer your question @corypride, @chrissantillan and I both thought that Student view should be the default.

**Comment by calisio** [comment]
UPDATE TO THIS TICKET: We have decided to split the users and the admin into two different pages. The refactoring of moving the tab view in the component will still exist as that might be needed in the future, but the new designs for these pages are linked [here](https://www.figma.com/design/a7VMBAXF2s385ogih8zjzl/Harvard-Mockups-Dark-Mode?node-id=4209-5837&node-type=frame&t=WnH7HfVWKEUs9K04-0).
