### ISSUE TITLE
Kiwix Management: Database Schema & Library Population

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#398]
**Description** 
* Create the `libraries` table in Postgres that will be used to persist Kiwix Open Content Libraries/Books.
* Build out a seed script to populate the `libraries` table with five Kiwix libraries. Use the [library feed](https://library.kiwix.org/catalog/v2/entries?lang=eng) from Kiwix to select five libraries. 

**Tasks**
- [x] Define the database schema for the `libraries` table
- [x] Implement the migrations to create the `libraries` table
- [x] Create the Go models for the `libraries` table
- [x] Write seeder scripts to populate the `libraries` table for development purposes

**Table structure**
Fields: (exact name can change if conventions require it, refer to similar database columns for types)
* `id` -- SERIAL internal identifier
* `open_content_provider_id` -- INT FK field to the `open_content_provider` table
* `external_id` -- VARCHAR? this field holds the external content provider's id
* `title` -- VARCHAR the name of the library
* `language` -- VARCHAR
* `description` -- TEXT description text for the library
* `href/url` -- VARCHAR this field holds the url that the user navigates to view the library
* `imageUrl` -- VARCHAR this field holds the url for the image
* `visibility_status` -- BOOLEAN this field reflects it this library is visible to users
* `created_at`
* `updated_at`
* `deleted_at`

**Acceptance criteria**
- The `libraries` table exists with the schema needed to support libraries.
- A row in the `open_content_provider` table exists for Kiwix.
- The seed script includes 5 libraries that are imported into the `libraries` table during `make seed`

[Link to Design in Notion](https://www.notion.so/unlockedlabs/Open-Content-Management-Design-5dcf69031dde4c909bd6528674346bc9?pvs=4)
