### ISSUE TITLE
Kiwix Management: Implement Library API Endpoints

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#399]
**Description**
- Implement the required API endpoints for both administrators and end-users to manage and retrieve libraries.
- Implement authorization checks in the backend to restrict endpoints to users with the appropriate permissions.

**Tasks**
- [x] Implement `GET /libraries` for administrators to retrieve all libraries, with optional filters.
- [x] Implement `PUT /libraries/{library_id}/visibility` for administrators to update the visibility of a specific library.
- [x] Implement `GET /libraries/visible` for all authenticated users to retrieve libraries that are visible, with optional filters.
- [x] Implement Test code to verify the API Handlers work as expected.

**Additional notes**
- `GET /libraries` and `PUT /libraries` ensures the requestor has administrator permission.
- `GET /libraries` supports filtering by open content provider id, title, or visibility status
- `GET /libraries/visible` supports filtering by open content provider id and title

**Acceptance criteria**
- All of the endpoints function as expected.
- Endpoint handlers include tests.

[Link to Notion Design Doc](https://www.notion.so/unlockedlabs/Open-Content-Management-Design-5dcf69031dde4c909bd6528674346bc9?pvs=4)
