### ISSUE TITLE
Kiwix Management: Implement Administrator UI

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#409]
Build out the Library Management Page for Administrators to manage the libraries available through open content providers such as Kiwix. Figma for this UI can be found [here](https://www.figma.com/design/a7VMBAXF2s385ogih8zjzl/UnlockEd-Mock-Ups?node-id=4277-10866&node-type=frame&t=LnmJsomYLmHKEwAp-0).

**Tasks**
- [x] Add navigation UI for the administrator to click on and browse the list of libraries to manage.
- [x] Create the Library Management Page for Open Content Providers
- [x] Implement functionality to view a list of libraries by fetching them from `GET /libraries`
- [x] Include support for filtering by content provider, title, or visibility
- [x] Implement functionality to toggle visibility for individual libraries with `PUT /libraries/{library_id}/visibility`

**Acceptance criteria**
* The page displays a list of libraries with their title, description, and visibility status.
* The admin can filter results by open content provider, title, or visibility.
* The administrator can change the visibility of a library and its setting is persisted across sessions.
