### ISSUE TITLE
Kiwix Management: Implement User UI for Library

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#410]
Build out the user interface for end users to see a list of available libraries in UnlockEd. Users will only be able to see a list of libraries that administrators have marked visible to them. Figma for this UI will look very similar to the [admin UI for libraries](https://www.figma.com/design/a7VMBAXF2s385ogih8zjzl/UnlockEd-Mock-Ups?node-id=4277-10866&node-type=frame&t=LnmJsomYLmHKEwAp-0), except it would filter out the cards that are "hidden".

**Tasks**
- [x] Add navigation UI for the user to click on and visit the library UI
- [x] Build a user-facing library page that shows all libraries (with title and description) that are set to visible. Data is from `GET /libraries/visible`

**Acceptance criteria**
- The user sees a navigation menu item to take them to open content libraries.
- The user sees a listing of libraries that they have access to because of the library's visibility setting.

**Comment by calisio** [comment]
REMINDERS:

- [ ] Remove `StaticContentCard.tsx` from codebase as this is not used anymore.
- [ ] Remove Open content column from student dashboard
