### ISSUE TITLE
Implement Facility Management UI

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#424]
Build out the front-end capabilities that allow an administrator to see a list of and manage facilities.

## Tasks
- [ ] Update the Facility model to include `location` (latitude, longitude)
- [x] Add a navigation link to the left-hand navigation, "Facilities" for admins.
- [x] Implement the Facilities List page to see a list of all facilities.
- [x] Include the pagination control for when the records need to be broken up over multiple pages.
- [x] Add a button for the user to Add a New Facility (and display an Add Facility Form)
- [x] Add an edit Button (and then display an Edit Form) next to each Facility
- [x] Add a delete button that prompts the admin to confirm the deletion

## User stories
* As an admin, I want to view a list of all Facilities so that I can manage them.
* As an admin, I want to add a new Facility by providing its name and location so that it becomes available in the system.
* As an admin, I want to edit the details of a Facility in case there's a mistake or something needs to change.
* As an admin, I want to disable (soft-delete) a Facility with a confirmation prompt so that I can remove it from active use without deleting historical data.

## Acceptance criteria
* When an admin is logged in, they see "Facilities" in the left-hand navigation. Users don't see the "Facilities" nav item.
* When a facility is deleted, it still exists in the database but has a deleted_at timestamp. It also doesn't show up in the UI.

## Notes
* There are a number of endpoints that will be relevant for this task:
  * `GET /api/facilities`
  * `GET /api/facilities{id}`
  * `POST /api/facilities`
  * `DELETE /api/facilities`
  * `PATCH /api/facilities/{id}`
* A new migration file will need to be created to add the location column(s) to the facility table.
* I would recommend starting by making this page resemble something like Provider Platforms, or Users Management
* Related tickets: 
  * https://github.com/UnlockedLabs/UnlockEdv2/issues/375
  * https://github.com/UnlockedLabs/UnlockEdv2/issues/380
