### ISSUE TITLE
Implement Facility Switching UI

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#425]
## Description
Develop the functionality that allows for administrators to select or switch the Facility they are currently managing.

## Tasks
- [x] Add a facility dropdown nested in the profile dropdown (where Users/Platforms/Resources/Logout is currently). See note.
- [x] Build component to change Facility context (calls `PUT /api/admin/facility-context/{id}`)
- [x] Validate that all UIs referencing facilities by name show the new selected facility.

## User stories
* As an admin, I want to select a Facility from a list so that I can manage data specific to that Facility.
* As a developer, I need to change the selected `facility_id` that is used with all claims in my auth token so that the backend returns the appropriate data.
* As an admin, when I switch Facilities, I want the data I see (e.g., users) to update accordingly so that I don't see irrelevant information.

## Acceptance criteria
* A dropdown or a similar UI element exists listing all of the Facilities the Admin has access to.
* When the admin changes facilities the header at the top of the page changes to the new Facility.
* Any page that includes facility-dependent data (e.g., users and administrators for now) are filtered to the new facility id.
* The application does not need to be refreshed when the facility is changed.

## Notes
* The active facility is currently stored on the client and provided with each request. It can be changed by calling `PUT /api/admin/facility-context/{id}`, which updates the user's claims with the new facility ID.
* We are not certain where to place a component that lets the user toggle the facility. @chrissantillan may have some ideas and should be involved as this is developed further.
  * **Idea 1:** In the Facilities List page, provide a button next to each facility for the admin to _Select_, which sets the active facility.
  * **Idea 2:** to the right of the facility name, add a dropdown (chevron) that lets the user switch between facilities.
  * _Note:_ This feature affects a limited population (i.e., a handful of users), and consideration should be given to what might happen as the number of facilities under management increases.
