### ISSUE TITLE
Kiwix Management: Implement a Backend Reverse Proxy 

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#431]
Modify the backend (written in Go) to serve as a reverse proxy for Kiwix library requests. The backend API will:
1. Validate that the user has authorization to view a library.
2. Forward the request to the open content provider if authorized.
3. Block access and return a 403 forbidden response if they don't have access. 
4. Allow for the library content to be viewed through UnlockEd, specifically in an `<iframe>`. 

**Tasks**
- [ ] Implement the Go Reverse proxy logic.
- [ ] Check for authorization access to Kiwix libraries.
- [ ] Ensure that requests are passed through the backend API
- [ ] Add an iFrame viewer to the UnlockEd frontend used when the user clicks on a library.
- [ ] Log that the Kiwix library was accessed through the reverse proxy.

**Acceptance criteria**
- Users can see and access Kiwix libraries through UnlockEd that they have permission to view.
- If a user tries to visit a specific page in UnlockEd that loads a library they don't have access to, they see some sort of forbidden page.
