### ISSUE TITLE
Create Department-wide Program

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#464]
# Create New Program & Mark Department-wide

As a Department-wide Program Coordinator (Admin) I want to create new programs that are department-wide so that these programs are available in every facility.

## Description

Create functionality in UnlockEd that allows the creation and management of Programs. Programs will include both educational courses (e.g., Hi-SET, college-level courses via Brightspace or Moodle) and rehabilitative offerings (e.g., therapy sessions, vocational training). These programs are going to be assigned to all facilities upon creation.

I am unsure if the best way to approach this task is to use some sort of department-wide flag so that it is always available to all facilities or to add a "Department-wide" checkbox that automatically checks all of the facilities.

### Task List

- [x] Update the Programs model with a Credit Type field and add a database migration for this new field.
- [x] Update the Programs model with a “Status” and “Program Type” fields and add a database migrations for these new fields.
- [x] Add Programs tab to the Admin Nav (check with #465 to see if this page is done)
  -  **Note** this Programs page (to view a list of programs) doesn't exist and will need to be completed as part of a separate task.
- [x] Create the Create Program form
  - Include fields for name, description, and credit type.
- [ ] Use the `POST api/programs` handler to create new Programs.

### Acceptance Criteria

* A user can create new programs in the system, including basic details (name, description, and credit type).
* A user can make the program department-wide.
* The program exists in the database and all of the data entered was captured.
* The program is assigned to all facilities in the system (upon creation).

### User Flow

* **Program Creation Flow:**
  * Coordinator logs into the system and navigates to the "Programs" tab in the admin dashboard.
  * Clicks “Create New Program.”
  * Enters basic program information (e.g., name, description, type).
  * Select credit type (e.g., Academic Credit, Participation Credit). 
    * For available credit types reach out to @chrissantillan on Slack.  
  * ~~Program is checked or set to be _department-wide._~~
  * Click "Save" to create the program.  

### Sample Program Data

Note this program data includes additional information beyond the scope of this ticket for presentation purposes.

```json
{
  "program_name": "Life Skills Program",
  "description": "A 10-week course focused on improving essential life skills.",
  "credit_type": "Participation Credit",
  "tags": ["Earned-Time Credit", "Certificate"],
  "facilities": ["Maine Correctional", "Mountain View Correctional"],
  "courses": [
    {
      "course_name": "Communication Skills",
      "lms": "Brightspace",
      "course_id": "BSPROG001"
    },
    {
      "course_name": "Financial Literacy",
      "lms": "Moodle",
      "course_id": "MDPROG002"
    }
  ],
  "sections": [
    {
      "section_name": "Life Skills - Section A",
      "schedule": "Monday and Wednesday, 9:00 AM - 11:00 AM",
      "location": "Classroom A"
    }
  ]
}
```

**Comment by jtucholski** [comment]
Available Credit Types include:
* Academic Credit
* Participation Credit
* Certificate of Completion
* Earned-Time Credit
* Rehabilitation Credit

**Comment by corypride** [comment]
@jtucholski @PThorpe92 @calisio should the form be called "Create Programs" or "Add Programs"

**Comment by calisio** [comment]
@corypride Lets go with "Add Program" for now, but I will double check with Chris.
