### ISSUE TITLE
Create New Program and Assign to Facility

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#468]
# Create New Program & Assign to Facilities

As a Department-wide Program Coordinator (Admin) I want to create new programs and assign them to facilities so that participants can see a list of education-based and rehabilitative programs available in their facility.

## Description

Create functionality in UnlockEd that allows the creation and management of Programs. Programs will include both educational courses (e.g., Hi-SET, college-level courses via Brightspace or Moodle) and rehabilitative offerings (e.g., therapy sessions, vocational training). These programs are going to be assigned to one or more facilities.

### Task List

**Note:** There is a lot of overlap in this task list with #464 

- [ ] Update the database scheme to create a many-to-many relationship between Program and Facility
- [ ] Update API & Tests to allow programs to be created and assigned to facilities.
  - Add an API Endpoint to get Programs by Facility (available to users and admins).
- [ ] Create (or update) the Create Program form
  - Include fields for name, description, and credit type.
  - Add a checkbox for the facilities. If the effort to add a(n) "Select all/Unselect all" checkbox is minimal include that.
- [ ] Use the `POST /api/programs` endpoint to create a new program (with assigned facilities)

### Acceptance Criteria

* A user can create new programs in the system, including basic details (name, description, and credit type).
* The program can be assigned to one or more facilities.
* The program exists in the database and all of the data entered was captured.

### User Flow

* **Program Creation Flow:**
  * Coordinator logs into the system and navigates to the "Programs" tab in the admin dashboard.
  * Clicks “Create New Program.”
  * Enters basic program information (e.g., name, description, type).
  * Select credit type (e.g., Academic Credit, Participation Credit).
  * Assign the program to one or more facilities (all facilities by default).
  * Click "Save" to create the program.  

### Sample Program Data

Note this program data includes additional information beyond the scope of this ticket for presentation purposes.

```json
{
  "program_name": "Life Skills Program",
  "description": "A 10-week course focused on improving essential life skills.",
  "credit_type": "Participation Credit",
  "tags": ["Earned-Time Credit", "Certificate"],
  "facilities": ["Maine Correctional", "Mountain View Correctional"],
  "courses": [
    {
      "course_name": "Communication Skills",
      "lms": "Brightspace",
      "course_id": "BSPROG001"
    },
    {
      "course_name": "Financial Literacy",
      "lms": "Moodle",
      "course_id": "MDPROG002"
    }
  ],
  "sections": [
    {
      "section_name": "Life Skills - Section A",
      "schedule": "Monday and Wednesday, 9:00 AM - 11:00 AM",
      "location": "Classroom A"
    }
  ]
}
```
