### ISSUE TITLE
Level 1 Access and navigation for Residents

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#487]
## User Story:

As a **Resident** with Level 1 access, I want to **log in and see a navigation menu limited to Open Content features**, so that I can focus on the resources available to me.

## Description:

This story focuses on the Resident's ability to log in and see only information relevant to Open Content (Level 1). The functionality they can access (either from their landing page or the navigation menu) is limited to browsing, searching, or viewing favorites for open content. 

All other application functionality that exists (e.g., Courses, Programs) aren’t visible to the resident. 

## Tasks:

- [ ]  Implement way of associating Residents to a list of features (or feature level) they can access.
- [ ]  Enforce API routes to require access to the features associated with Level 1 Open Content
- [ ]  Implement dynamic navigation menu to display items based on user’s role & feature permissions
- [ ]  Show basic landing page (dashboard) for residents after log in
- [ ]  Add route guards to block users from accessing features they cannot use

## User Flow:

**Login**

1. Resident logs in using their credentials.
2. System determines role and feature permissions.
3. Resident is directed to the dashboard, which only displays features associated with Open Content.
    1. Dashboard
    2. Open Content (libraries page)
    3. Favorites (links to open content favorites page)

**Resident tries to access page that isn’t available to them**

1. When the resident tries to access a restricted URL, the system blocks access and displays an error message.

## Considerations

I don’t know if there will be a future need to define more granular-level feature permissions within a single deployment. Ideally we avoid making significant architectural decisions that restrict that.

## Acceptance Criteria:

- Residents with access to Open Content Management features see those listed in the Navigation menu.
    - Dashboard
    - Open Content
    - Favorites
- Features such as Courses, Programs are hidden from the navigation.
- Backend API endpoints are blocked if not in Level 1
