### ISSUE TITLE
Level 1 Access and navigation for Administrators

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#488]
## User Story:

As an **Administrator** with Level 1 access, I want to **log in and be able to manage open content**, so that I can manage what resources are available to residents.

## Description:

This story focuses on the Administrator's ability to log in and manage information relevant to Open Content (Level 1). The functionality they can access—either from the landing page or the navigation menu—is limited to a dashboard displaying open content information, resident management, admin management, and resource management. 

Other application features, such as Provider platforms and Course catalog, are not visible to an administrator.

## Tasks:

- [ ]  Implement way of associating Administrators to a set of features (or feature level) they can access.
- [ ]  Enforce API routes to require access to the features associated with Level 1 Open Content, Resource Management, User management
- [ ]  Implement dynamic navigation menu to display items based on user’s role & feature permissions
- [ ]  Show basic landing page (dashboard) for residentsLayer 1 admins during log in
- [ ]  Add route guards to block users from accessing features they cannot use

## User Flow:

**Login**

1. Administrator logs in using their credentials.
    1. System determines role and feature permissions.
2. Administrator is directed to the dashboard.
    1. Dashboard includes visuals associated with Open Content usage for the selected facility.
    2. Navigation includes: Resident management, Admin management, Open content management, and Resource Management

**Administrator tries to access page that isn’t available to them**

1. When the resident tries to access a restricted URL, the system blocks access and displays an error message.

## Considerations

I don’t know if there will be a future need to define more granular-level feature permissions within a single deployment. Ideally we avoid making significant architectural decisions that restrict that.

## Acceptance Criteria:

- Administrators with access to Open Content Management features see those listed in the Navigation menu.
    - Dashboard
    - Open Content Management
    - Resident Management
    - Resource Management
    - Admin Management
- Features such as Courses, Programs are hidden from the navigation.
- Backend API endpoints are blocked if not in Level 1
