### ISSUE TITLE
Manage product level for deployment

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#489]
## User Story:

As a **System Administrator**, I want a way to **toggle the product level** for a deployment, so that I can manage what features users have access to without involving IT.

## Description:

This story focuses on Unlocked Labs' ability to manage feature levels (Level 1, Level 2, or Level 3) available to users in a given deployment. It is motivated by the following needs: 

- Simplifying deployments by having one deployment with various features that can be locked or unlocked.
- Demonstrating and selling the product based on customer interest by showcasing relevant features.
- Making changes without requiring IT intervention.

In a SaaS product, this is analogous to a customer's product plan, which determines the features they see upon login. While there are no current requirements for different feature levels by user or facility, it would be ideal to avoid architectural decisions that might limit this ability in the future.

## Tasks:

- [ ]  Implement a back-end feature flag system that supports enabling or disabling features.
- [ ]  Implement middleware/API route check framework to validate requests have access to feature flags.
- [ ]  Implement front-end route guards to verify active user can access pages.
- [ ]  Create an administration page to active/deactivate feature flags.

## User Flow:

- **Modify Feature Access**
    - System administrator logs into the system and sees navigation option for “Feature Management”
    - SA toggles feature on or off for the active instance and saves changes.
    - Users see updated navigation menus and access based on the new feature configuration.

## Acceptance Criteria:

- The system administrator can log in and enable/disable specific features such as Open Content, Course Management, Program Management.
    - Administrators cannot make these changes.
- The changes take effect immediately without requiring a deployment.

**Comment by jtucholski** [comment]
#487 and #488 are directly dependent on this.
