### ISSUE TITLE
Resident dashboard > Display top N libraries

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#491]
## User Story:

As a **Resident**, I want to **see my top 5 libraries on my dashboard**, so that I can quickly read open content after logging in.

## Description:

This task involves creating a dashboard component that renders the user’s top 5 open content libraries that they browse.

Depending on what [[Track library activity](https://www.notion.so/Track-library-activity-13701ac3401f806ab585fbb4a46ef84f?pvs=21)](https://www.notion.so/Track-library-activity-13701ac3401f806ab585fbb4a46ef84f?pvs=21) captures, this would be determined by which libraries receive the most page requests. Users would be able to filter based on time.  

## Tasks:

- [ ]  Implement API endpoint (i.e., `GET /api/dashboard/library-activity`) to retrieve library activity data.
- [ ]  Implement database query to retrieve library activity by user with filters (7 days, 30 days, 90 days, 6 months, 12 months). Limit to top 5 libraries.
- [ ]  Build React component to display top libraries.
    - Consider what to display when there aren’t 5 libraries to display.
    - The visual spacing of the component should be the same whether there is 1 library or 5 libraries.

## User Flow:

**User logs in or visits Dashboard**

- The user sees a "Top Libraries" component on their dashboard, displaying up to 5 of their most visited libraries.
    - Libraries are listed in descending order based on the number of page visits.
    - The default sorting period is 7 days.
    - Each library entry includes a thumbnail and the library's name.

## Acceptance Criteria:

- Residents can view their top 5 most visited libraries based on the number of page requests.
- Time filters include: past 7 days, 30 days, 90 days, 6 months, and 12 months.
- The default time filter is 7 days.
- The dashboard updates insights based on the selected time frame.
- Libraries in this list that have been disabled should appear greyed out or have the label “Disabled” next to it.

**Comment by jtucholski** [comment]
Depends on #490
