### ISSUE TITLE
Resident Dashboard > Display Top N Libraries for Facility

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#492]
## User Story:

As a **Resident**, I want to **see the top 5 libraries viewed at my facility**, so that I can see what others around me are often reading.

## Description:

This task involves creating a dashboard component that renders the top 5 open content libraries tracked by users at the facility level.

Depending on what [[Track library activity](https://www.notion.so/Track-library-activity-13701ac3401f806ab585fbb4a46ef84f?pvs=21)](https://www.notion.so/Track-library-activity-13701ac3401f806ab585fbb4a46ef84f?pvs=21) captures, this would be determined by which libraries receive the most page requests. Users would be able to filter based on time.  

## Tasks:

- [ ]  Implement API endpoint (i.e., `GET /api/facility/{id}/library-activity`) to retrieve library activity data.
- [ ]  Implement database query to retrieve library activity by user with filters (7 days, 30 days, 90 days, 6 months, 12 months). Limit to top 5 libraries.
- [ ]  Build React component to display top libraries.
    - Consider what to display when there aren’t 5 libraries to display.
    - The visual spacing of the component should be the same whether there is 1 library or 5 libraries.

## User Flow:

**User logs in or visits Dashboard**

- The user sees a "Top Libraries in your facility" component on their dashboard, displaying the top 5 most visited libraries for the user’s facility.
    - Libraries are listed in descending order based on the number of page visits.
    - The default sorting period is 7 days.
    - Each library entry includes a thumbnail and the library's name.

## Acceptance Criteria:

- Residents can view the top 5 most visited libraries based on the number of page requests.
- Time filters include: past 7 days, 30 days, 90 days, 6 months, and 12 months.
- The default time filter is 7 days.
- The dashboard updates insights based on the selected time frame.
- Libraries in the list that have are no longer “visible” should have the label Disabled next to it and be greyed out.

**Comment by jtucholski** [comment]
Depends on #490
