### ISSUE TITLE
Allow Residents to Favorite Libraries

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#493]
## User Story:

As a **Resident**, I want to **favorite libraries**, so that I can easily access them later.

## Description:

This story involves introducing functionality that makes it possible for residents to “favorite” libraries that they may regularly visit or come back to.

All favorite libraries can be viewed on the Open Content page. In another story, [[Dashboard > Display “favorited” libraries](https://www.notion.so/Dashboard-Display-favorited-libraries-13601ac3401f8039a084e466a3c176d3?pvs=21)](https://www.notion.so/Dashboard-Display-favorited-libraries-13601ac3401f8039a084e466a3c176d3?pvs=21) users will be able to see their favorited libraries on the Dashboard page and also have a link that navigates them to the Open Content > Favorites view.

## Tasks:

- [x]  Add a database migration to allow for users to favorite open content.
- [x]  Expose API endpoint (i.e., `PUT /api/open-content/{id}/save`) operations that allow a user to favorite/unfavorite an open content item.
- [x]  Expose API endpoint operations that retrieve a user’s favorited open content items.
- [x]  Add Favorites tab to Open Content page to display favorited libraries.
- [x]  Update the Open Content page to allow Residents ability to “favorite” an open content library.

## User Flow:

**Resident toggles favorite setting for an open content library**

- The resident visits the Open Content page.
- Libraries that are favorited display a filled-in bookmark icon.
- Libraries that aren't favorited show a transparent bookmark outline.
- Residents can click on an Open Content library's bookmark button to favorite or unfavorite it.

**User views open content favorites**

- Resident navigates to the Open Content > Favorites page
- All favorited libraries are displayed on this page
- Resident can unfavorite library from this page and it is removed from their view.

**Favorited content is disabled by administrator**

- Precondition: A user has favorited an open content library that an administrator has since disabled.
- User visits the Open Content > Favorites page.
- Previously visible libraries that are now disabled appear grayed out with a "Disabled" label.
- User can remove these libraries from their favorites.

## Acceptance Criteria:

- The Resident can visit a page under Open Content that shows their favorited open content libraries.
- The Resident can favorite/unfavorite open content libraries.
- Any favorited libraries that have been hidden by administrators still show but are visible marked indicating they are disabled.
