### ISSUE TITLE
Layer 1 Admin Dashboard (Knowledge Insights) > View Dashboard of open content usage

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#504]
## User Story:

As an **Administrator**, I want to **view a dashboard showing the most used and favorited libraries and content**, so that I can understand resident engagement.

## Description:

This task involves creating Administrator versions of the Resident Trending Content components. The Administrator Knowledge Insights page will display two key components: the top 10 most visited libraries (with date filters) and the top 10 most favorited libraries.

## Tasks:

- [ ]  Determine if existing API endpoints exist to retrieve top 5 libraries and top 5 favorited libraries (by facility). Add if they don’t.
- [ ]  Build Knowledge Insights component to display top 5 visited libraries for the current facility.
    - Knowledge Insights component supports additional filter levels (past 7 days, past 30 days, past 90 days, past 6 months, and past 12 months)
    - List includes libraries that are marked as hidden/disabled.
- [ ]  Build Knowledge Insights component to display top 5 favorited libraries for the current facility.
    - List displays the favorited libraries in descending order (with most favorites first)
    - List includes libraries that are marked as hidden/disabled.

## Sample Diagram:

![Image](https://github.com/user-attachments/assets/89ebb8af-5c13-4f25-a564-158dab1025a8)

## User Flow:

- **Administrator logs in.**
    - Landing page is the Knowledge Insights page. They also see a Knowledge Insights navigation item.
- **Viewing Top 10 Visited Libraries**
    - The Knowledge Insights page displays a component for the “Top 10 Visited Libraries”
    - By default, the data for the past 7 days is shown.
    - The administrator can use different date filters to change the date range.
    - If the administrator changes the selected facility on the page, the dashboard components reflect the new facility.
- **Viewing Top 10 Favorited Libraries**
    - Alongside (or below) the Visited Libraries, a “Top 10 Favorited Libraries” component is displayed.
    - This component shows libraries most frequently added to residents’ favorite lists.
    - If the administrator changes the selected facility on the page, the Knowledge Insights components reflect the new facility.

## Acceptance Criteria:

- The Knowledge Insights page displays Top 10 Visited Libraries using the current facility and the selected date range.
- The Knowledge Insights page displays Top 10 Favorited libraries using the current facility.

**Comment by jtucholski** [comment]
Featured Libraries (if more than 4) can be scrolled through using a carousel component.

**Comment by calisio** [comment]
There are a few things that don't align here- do you want the top 10 or top 5 of each of these libraries. Also, to confirm, do you want featured libraries displayed?
