### ISSUE TITLE
Layer 1 Resident Dashboard > Display featured open-content libraries

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#507]
## User Story:

As a **Resident,** I want to **see curated open content libraries on my dashboard**, so that I can quickly read content the administration believes is most effective.

## Description:

Administrators can curate specific content libraries for residents (depends on https://github.com/UnlockedLabs/UnlockEdv2/issues/506). This feature brings those curated libraries to the Dashboard. Due to limited space, the Dashboard component should display 3 libraries at random, depending on available visual space. 

When a user clicks on one of these libraries, they are taken directly to the open content viewer.

## Tasks:

- [ ]  Build a Dashboard component to display curated content
    - The title of the component should display “**Featured Content”**
    - The component should display 3 items.
    - Display a card w/link to Open Content if there are less than 3 featured items.
- [ ] Build a "Featured Content" tab on the Content page that displays all of the items an admin has featured.
- [ ]  Invoke the API endpoint to retrieve curated content
    - Make sure that the library is set to *visible*.

## User Flow:

- **Viewing Featured Libraries**
    - The resident logs into UnlockEd.
    - On their dashboard they see a dashboard component that displays Featured Libraries

## Acceptance Criteria:

- A resident logs in and sees a dashboard component called **Featured Libraries** that shows up to 3 libraries.
    - These libraries were marked as featured by an Administrator.
- If there are fewer than three cards featured then a card with a link to the Open Content page is shown.
