### ISSUE TITLE
Brightspace > Resident-to-Student Mapping

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#522]
## User Story:

As a **System Administrator**, I want **the ability to map resident users in UnlockEd to corresponding student accounts in Brightspace**, so that Residents see and access their Brightspace courses from UnlockEd.

## Description:

This task ensures System Administrators can integrate UnlockEd with Brightspace LMS and map user accounts between the systems. While most of this work is likely complete, the focus is on identifying and addressing any gaps between the current and desired functionality.

## Tasks:

- [x]  Add Brightspace as a provider in the Add Provider screen
    - Capture required fields like base url, account id, or access key
- [x]  Implement functionality to map users (inserting users into `provider_user_mappings`)
- [x]  Implement functionality to remove mapping from an UnlockEd user to Brightspace Student account.

## User Flow:

- Administrator clicks **Add Provider** to add a new Brightspace integration
    - The `type` dropdown includes Brightspace LMS
    - The Administrator fills in required fields relevant to integrating w/Brightspace LMS.
- Administrator clicks **Map User** on an UnlockEd user
    - The Administrator can search for and map the UnlockEd user to a Brightspace user

## Acceptance Criteria:

- Administrator can map an UnlockEd user to a Brightspace Student account
- Administrator can remove a mapping from an UnlockEd user.
- The provider_platform_mapping table is updated with the new mapping.

## Additional Notes:

- If there is development work associated with this task then convert this to a GitHub issue and link it in the PR.
