### ISSUE TITLE
My Courses > View Additional Course Details for External Courses

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#525]
## User Story:

As a Resident, I want to see additional details for each external course (e.g., start and end dates) in addition to the basic details (course name, LMS name) in UnlockEd, so that I understand what each course covers and when it takes place.

## Description:

This issue focuses on enhancing the course list in UnlockEd to display **additional details for external courses** from integrated platforms. Residents will be able to view start and end dates.

## Tasks:

- [x]  Extend the external course integration API handler to fetch course metadata, including:
    - Start date
    - End date
- [x]  Update the course list UI in the dashboard to include columns/sections for:
    - Start date
    - End date
- [x]  Add filtering or sorting option by course start and end dates, if  possible.

## User Flow:

1. **Resident Logs In**:
    - The resident logs into UnlockEd and navigates to their course list.
2. **View Course List**:
    - The resident sees a list of their active courses, with each course displaying:
        - Course name
        - Start date
        - End date
        - LMS source (e.g., Brightspace)

## Sample Program Data:

```jsx
[
  {
    "course_name": "Introduction to Financial Literacy",
    "start_date": "2024-01-15",
    "end_date": "2024-03-15",
    "lms_source": "Brightspace",
    "course_id": "BRIGHT_001"
  },
  {
    "course_name": "GED Preparation - Mathematics",
    "start_date": "2024-02-01",
    "end_date": "2024-06-01",
    "lms_source": "Brightspace",
    "course_id": "BRIGHT_123"
  },
  {
    "course_name": "Communication Skills for Career Success",
    "start_date": "2024-01-10",
    "end_date": "2024-03-30",
    "lms_source": "Brightspace",
    "course_id": "BRIGHT_045"
  }
]
```

## Acceptance Criteria:

- The external course API integration successfully fetches metadata for all active courses, including course name, start date, and end date.
- The resident course list displays:
    - Course name
    - Start date
    - End date
    - LMS source (e.g., Brightspace or Moodle)

**Comment by carddev81** [comment]
After a bit of research Kolibri does not have any start or end dates for channels/classes.  Brightspace and Canvas both have start/end dates.
