### ISSUE TITLE
Knowledge Center > Helpful Links

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#526]
## User Story:

As a **Resident,** I want the ability to **see additional helpful links in the same location as other learning materials** so that I can easily find and engage with the content. ****

## Description:

We will repurpose the Resource Management feature from the current UnlockEd version. 

Currently, administrators can share additional resources (beyond Libraries and Videos) with Residents through the Resource Management page, which displays links on the resident dashboard. In the new update, these resources will be accessible through a new *Helpful Links* tab in the Knowledge Center.

Each link requires a title and URL. Administrators can add, edit, and delete links, with the ability to sort them alphabetically in ascending or descending order. Adding website favicons to the links would be a useful enhancement (it is not required).

Residents can access and favorite these resources through the *Helpful Links* tab, similar to how they interact with libraries and videos. The system will track when residents click on links, allowing administrators to monitor which resources are most frequently accessed through UnlockEd. 

## Tasks:

- [x]  Create a Helpful Links tab
    - Allow Administrators to Add links.
        - Administrators must provide the title and URL.
        - New links are visible by default.
    - Allow Administrators to Edit and Delete links.
    - Provide a UI to see the list of links that is similar to the Libraries or Videos.
    - Administrators must be able to change link visibility to Hidden or Visible.
- [x]  Allow links to be sorted (ascending/descending) by date added or title.
- [x]  Capture activity when a Resident clicks on a link through the Knowledge Center or the Dashboard.
- [x]  Clean up the Resource Management page and the Resource Links on the Dashboard side bar.
- [x]  Remove any components, handlers, and models that were solely created for the Resource Management page.

## Acceptance Criteria

- Administrator can add, edit, and delete links from the Knowledge Center.
- Administrator can control visibility for each link in the Knowledge Center.
- Administrator/Resident can sort the links by date added or title.
- The system captures when a Resident clicks on a link and logs it as Activity.

## User Flow:

1. **Access the Knowledge Center**:
    - The resident logs in to UnlockEd and clicks the **Knowledge Center** link in the main menu.
2. **Browse Content by Category**:
    - The resident sees tabs for **Libraries**, **Videos**, and **Helpful Links** and clicks on the **Helpful Links** tab to explore its content.
    - They can browse lists of links, each with a title and description.
    - When they click on a link, the system tracks the click event as activity (similar to viewing a Library or Video) while navigating them to the destination.
3. **Manage Content** 
    - The administrator sees tabs for **Libraries**, **Videos**, and **Helpful Links** and clicks on the **Helpful Links** tab to manage the links.
    - The administrator can click Hidden or Visible buttons to hide or show links.
    - The administrator can click **Add Link** to add a new link.
    - The administrator can click **Edit** ✏️ ****on a link to edit an existing link.
    - The administrator can click **Delete** 🗑️ on a link to delete an existing link.
4. **Adding a Link**
    - The administrator provides a title and a URL to add a new link.
    - The system fetches the favicon (nice to have) and then updates the page with the new link.
5. **Editing a Link**
    - The administrator corrects the title or URL and clicks **Add Link**.
    - The system fetches the favicon (nice to have) and then updates the page with the new link.
6. **Deleting a Link**
    - The system prompts the administrator if they want to delete the link.
    - The administrator confirms they want to delete it and the system removes the link from the page.
