### ISSUE TITLE
Favoriting Helpful Links

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#554]
## User Story:

As a **Resident**, I want to **favorite Helpful Links**, so that I can quickly access external resources or content I find most useful or engaging.

## Description:

This issue introduces functionality to allow residents to favorite **Helpful Links** from the Knowledge Center page. Helpful Links are external resources that residents may want to revisit regularly. Once favorited, they will be accessible from the Favorites section of the Resident dashboard, alongside other favorited content types (e.g., Libraries and Videos).

Residents will be able to:

- Mark Helpful Links as favorites by toggling a favorite (star) icon.
- Unfavorite Helpful Links at any time, removing them from their Favorites sidebar.

## **Tasks:**

- [x]  Add a database migration to create a table for favoriting Helpful Links.
- [x]  Expose API endpoint (i.e., `PUT /api/<name>/{id}/save`) operations that allow a user to favorite/unfavorite a Helpful Link.
- [x]  Update API endpoint (`/api/open-content/favorites`)to include helpful
(i.e., `GET /api/helpful-links/favorites`) that retrieve a user’s favorited Helpful Links.
- [x]  Update the Knowledge Center page to allow Residents ability to “favorite” a Helpful Link.
- [x]  Perform any work necessary to update Layer 1 Dashboard “Favorites” component to include Helpful Links.

## User Flow:

**Resident toggles favorite setting for a Helpful Link**

1. Resident visits the Knowledge Center page.
2. Helpful Links that are favorited display a filled-in star icon.
3. Helpful Links that aren't favorited show a transparent star outline.
4. Resident clicks on a Helpful Link's star button to favorite or unfavorite it.

**Resident views favorited Helpful Links**

1. Resident navigates to the Knowledge Center dashboard.
2. All favorited Helpful Links are displayed alongside favorited Libraries and Videos.

## **Acceptance Criteria**

- Residents can favorite/unfavorite Helpful Links on the Knowledge Center page.
- Backend endpoints return favorited Helpful Links correctly for the logged-in resident.
