### ISSUE TITLE
RESEARCH: Search within libraries

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#558]
## Description

This research explores the effort required to offer residents the ability to search the contents of a specific library for specific keywords.

If you visit [library.kiwix.org](http://library.kiwix.org/) and navigate to a library you’ll see a search box is available
 ![Image](https://github.com/user-attachments/assets/42bd52f0-0af6-4855-966d-502e4aa8cfd4)

You can see what the results look like. [Search: experiment](https://library.kiwix.org/viewer#search?books.name=rationalwiki_en_all_nopic_2021-03&pattern=experiment). We want to offer a capability like this to Residents so it becomes easier for them to locate information inside of these ZIM files. 

Ideally the research addresses:

1. If we can leverage the existing search that Kiwix offers or need to build our own.
2. What search interface we add to UnlockEd for users.
3. How to continue to log/track links and libraries that the user accesses.

The outcome of this research will be a **draft issue** outlining the implementation approach, including task breakdowns for development.

**Note:** There is a separate issue that involves looking into [RESEARCH: Search across libraries](https://github.com/UnlockedLabs/UnlockEdv2/issues/559). 

## Tasks

- [x]  Explore options that Kiwix already offers for search
- [x]  If necessary, explore alternative options for searching libraries.
- [x]  Determine what changes need to be made to the Knowledge Center page/components to support searching within libraries.
- [x]  Identify API changes or additions that need to be made for Knowledge Center search.

## Acceptance Criteria

- A detailed draft GitHub issue is created, outlining the proposed approach and effort for implementing “Search within Libraries” based on the research here.
- The draft issue includes:
    - Whether or not we can build off of the Kiwix implementation of search.
    - Backend and frontend development tasks with clear objectives (e.g., components, API handlers, migration changes needed, etc.)
    - Identified risks or challenges that we foresee would come with this integration path.
    - Options that we considered and chose not to do.
- The issue also identifies if there are any dependencies (e.g., technical debt or other issues) that must be addressed before implementing search.

**Comment by carddev81** [comment]
Created draft issue per Chris:  https://github.com/UnlockedLabs/UnlockEdv2/issues/585

Also created gist with same info:  https://gist.github.com/carddev81/8c0faba3101293724442c7a54fb95ea7
