### ISSUE TITLE
RESEARCH: Search across libraries

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#559]
## Description

This research explores implementing search functionality across all libraries using keywords.

Unlike [RESEARCH: Search within libraries](https://github.com/UnlockedLabs/UnlockEdv2/issues/558), which focuses on searching within a single library similar to Kiwix's current functionality, this feature would allow searching across multiple libraries simultaneously.

Users would not need to specify a library before searching, though results would be limited to libraries they can access.

Results can be grouped by library rather and do not need to be ranked for relevance across all libraries. Users should have a way to page through the results if there are too many for one screen. 

The research should address:

1. Available options for implementing cross-library search capabilities
2. Potential risks, including costs, performance impact, and security concerns
3. Required frontend and backend modifications
4. Possible technical challenges during implementation
5. Estimated timeline for complete implementation

The research will result in a **draft issue** that outlines the proposed implementation approach and may generate multiple tickets. All known development tasks should be included.

## Tasks

- [x]  Explore if Kiwix already offers this capability in some manner and if there’s a way that we can leverage it. These issues [#704 Add book titles to search results](https://github.com/kiwix/libkiwix/issues/704), [#478 kiwix-serve should inform the user which zim file/website their search result came from](https://github.com/kiwix/kiwix-tools/issues/478) imply that it might already exist.
- [x]  Research similar applications that might offer this capability and explore how they might implemented it if possible.
- [x]  Determine what changes need to be made to the Knowledge Center and pages/components to support searching across libraries and rendering results.
- [x]  Identify API changes or new endpoints to support search.

## Acceptance Criteria

- A detailed draft GitHub issue is created, outlining the proposed approach and effort for implementing “Search within Libraries” based on the research here.
- The draft issue includes:
    - Whether or not we can build off of the Kiwix implementation of search.
    - Backend and frontend development tasks with clear objectives (e.g., components, API handlers, migration changes, etc.)
    - Identified risks or technical challenges that we might encounter with this feature.
    - Other options (if applicable) we considered and chose not to use.
- The issue also identifies if there are any dependencies (e.g., technical debt or other issues) that must be addressed before implementing search.

**Comment by carddev81** [comment]
Created draft issue per Chris:  https://github.com/UnlockedLabs/UnlockEdv2/issues/586

Also created gist with same info:  https://gist.github.com/carddev81/be80976323212df2a25b9818de151502
